# Generated by Django 6.0.4 on 2026-04-16 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.engineer')),
            ],
        ),
    ]
