# Generated by Django 6.0.4 on 2026-04-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='period',
            field=models.CharField(choices=[('morning', '上午'), ('afternoon', '下午'), ('full', '全天')], default='full', max_length=10),
            preserve_default=False,
        ),
    ]
