# Generated by Django 6.0.4 on 2026-04-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_engineer_user_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
