# Generated by Django 6.0.4 on 2026-04-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_dispatchorder_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='指定時間'),
        ),
    ]
