# Generated by Django 6.0.4 on 2026-04-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_dispatchorder_note_dispatchorder_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchorder',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='指定時間'),
        ),
    ]
