# Generated by Django 6.0.4 on 2026-04-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_alter_dispatchorder_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='到職日'),
        ),
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.FloatField(default=0.5, verbose_name='請假天數'),
        ),
    ]
